### ISSUE TITLE
Using Unicorn https by pass forCloudflare DNS

### ISSUE THREAD

**Issue by Geeffrey** [nucypher/protocol#19]
I am having a.hardtime Everytime I am signing in with my Cloudflare account..it keeps on asking Authentication password number, so I had downloaded Authy two-factor authentication..can it be possible to synchronized my Cloudflare account directing Authy to auto connect log in?

**Comment by tuxxy** [comment]
This issue isn't related to NuCypher. Perhaps you have the wrong repo?
